In [ ]:
!pip install wikipedia

Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from wikipedia) (4.11.2)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wikipedia) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2023.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->wikipedia) (2.5)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=0fe11089fceba945688532fe5aa65bb25f59e171081d37c1c88a82db17df06d5
  Stored in directory: /root/.cache/pip/wheels/5e/b6/c5/93f3dec388ae76edc830cb42901bb0232504dfc0df02fc50de
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0

In [ ]:
import wikipedia

In [ ]:
wikipedia.set_lang("ru")

In [ ]:
gagarin_page = wikipedia.page("Юрий Гагарин")

In [ ]:
type(gagarin_page)

wikipedia.wikipedia.WikipediaPage

In [ ]:
dir(gagarin_page)

['_WikipediaPage__continued_query',
 '_WikipediaPage__load',
 '_WikipediaPage__title_query_param',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'categories',
 'content',
 'coordinates',
 'html',
 'images',
 'links',
 'original_title',
 'pageid',
 'parent_id',
 'references',
 'revision_id',
 'section',
 'sections',
 'summary',
 'title',
 'url']

In [ ]:
print(gagarin_page.title)

Гагарин, Юрий Алексеевич

In [ ]:
print(gagarin_page.url)

https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%B3%D0%B0%D1%80%D0%B8%D0%BD,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87

In [ ]:
print(gagarin_page.content[:1000]) # Что делает этот код?

Ю́рий Алексе́евич Гага́рин (9 марта 1934, Клушино, Гжатский (ныне Гагаринский) район, Западная область (ныне — Смоленская область) — 27 марта 1968, возле села Новосёлово, Киржачский район, Владимирская область) — лётчик-космонавт СССР, Герой Советского Союза, кавалер высших знаков отличия ряда государств, почётный гражданин многих российских и зарубежных городов.
Полковник ВВС СССР (1963), военный лётчик 1-го класса, заслуженный мастер спорта СССР (1961), член ЦК ВЛКСМ, депутат Верховного Совета СССР 7-го и 8-го созывов.
12 апреля 1961 года Юрий Гагарин стал первым человеком в мировой истории, совершившим полёт в космическое пространство. Ракета-носитель «Восток» с кораблём «Восток-1», на борту которого находился Гагарин, была запущена с космодрома Байконур, расположенного в Кызылординской области Казахской ССР. После 108 минут полёта Гагарин успешно приземлился в Саратовской области, неподалёку от Энгельса. 12 апреля 1961 года, день полёта Юрия Гагарина в космос, был объявлен праздник

In [ ]:
 wikipedia.random(10)# ваш код здесь

['Восстание шейха Саида',
 'Маклаковский заказник',
 'Стегний, Алексей Григорьевич',
 'Бакарджиев, Вячеслав Георгиевич',
 'Байтемиров, Насирдин',
 'Большаков, Андрей Владимирович',
 'Гинкас, Кама Миронович',
 '1626 год в науке',
 'Шадринская епархия',
 'Военинженер 1-го ранга']

In [ ]:

from IPython.display import Image# Эта строка и строка ниже позволят показывать картинки внутри ноутбука.
from IPython.core.display import HTML
 # Загрузите нужную страницу.
page=wikipedia.page(title="Париж", pageid=None, auto_suggest=True, redirect=True, preload=True)
print(page.url)
image_link='https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/1920px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg'
Image(url=image_link)

https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%B8%D0%B6

In [ ]:
page=wikipedia.page(title="остров Пасхи, Чили", pageid=None, auto_suggest=True, redirect=True, preload=True)# ваш код здесь
print(dir(page))
print(page.url)
print(page.coordinates)
(lan, lon)=page.coordinates
wikipedia.geosearch(lan, lon, results=10, radius=10)

['_WikipediaPage__continued_query', '_WikipediaPage__load', '_WikipediaPage__title_query_param', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', '_images', '_links', '_parent_id', '_references', '_revision_id', '_sections', '_summary', 'categories', 'content', 'coordinates', 'html', 'images', 'links', 'original_title', 'pageid', 'parent_id', 'references', 'revision_id', 'section', 'sections', 'summary', 'title', 'url']
https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D1%82%D1%80%D0%BE%D0%B2_%D0%9F%D0%B0%D1%81%D1%85%D0%B8
(Decimal('-27.11670000000000158024704433046281337738037109375'), Decimal('-109.349999999999994315658113919198513031005859375'))

['Субтропический широколиственный лес острова Пасхи',
 'Остров Пасхи',
 'Исла-де-Паскуа (провинция)']

In [ ]:
dir(wikipedia)# ваш код здесь
sorted(wikipedia.languages().values())
d=sorted(wikipedia.languages().values())
print(len(d)+1)

518

In [ ]:
gagarin_page = wikipedia.page("Юрий Гагарин")# ваш код здесь
evklid_page = wikipedia.page("Евклид")# ваш код здесь
print(gagarin_page.url)
print(gagarin_page.links)
d1=gagarin_page.links
print(len(d1)+1)
d1=evklid_page.links
print(len(d1)+1)
rezult=(list(set(gagarin_page.links)&set(evklid_page.links)))
print(rezult)
print(len(rezult)+1)

https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%B3%D0%B0%D1%80%D0%B8%D0%BD,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87
['(1772) Гагарин', '122-я истребительная авиационная дивизия', '12 апреля', '1934 год', '1961 год', '1968 год', '1976', '2023 год', '27 марта', '30 марта', '40-летие космического полёта Ю. А. Гагарина (монеты)', '769-й истребительный авиационный полк', '9 марта', 'CiNii', 'Foreign Broadcast Information Service', 'Gemeinsame Normdatei', 'Internet Movie Database', 'Joint Publications Research Service', 'NASA', 'NUKAT', 'RTVI', 'Rolls-Royce Silver Cloud', 'Sports.ru', 'Sukhoi Superjet 100', 'UTC', 'VIAF', 'Vice (журнал)', 'W. W. Norton & Company', 'Wayback Machine', 'WorldCat', 'YouTube', 'Абдель Хаким Амер', 'Абрамов, Анатолий Петрович (учёный)', 'Авангардная музыка', 'Авиамарш', 'Австрия', 'Автово (исторический район)', 'Агальцов, Филипп Александрович', 'Адъюнктура', 'Азербайджан', 'Азов', 'Аксёнов, Владимир Викторович', 'Алгоритм (издательство)', 'Александрия', 'Александров, Александр Павлович (космонавт)', 'Алексей Иванович Гагарин', 'Алма-Ата', 'Алма-Атинская швейная фабрика имени Гагарина', 'Альмерек', 'Алёша (памятник, Пловдив)', 'Амурская область', 'Ан-10', 'Анастасия Степановна Гагарина', 'Англия', 'Ангола', 'Андреевский погост', 'Анна Егоровна Матвеева', 'Антарктида', 'Аполлон-15', 'Аргументы и факты', 'Артюхин, Юрий Петрович', 'Арцебарский, Анатолий Павлович', 'Астронавт', 'Атьков, Олег Юрьевич', 'Аубакиров, Токтар Онгарбаевич', 'Афанасьев, Виктор Михайлович', 'Афины', 'Байконур', 'Байконур (город)', 'Баландин, Александр Николаевич', 'Балашихинский литейно-механический завод', 'Баллистический спуск', 'Батурин, Юрий Михайлович', 'Башкортостан', 'Безымянка (аэродром)', 'Белопольский, Яков Борисович', 'Белоцерковский, Сергей Михайлович', 'Беляев, Павел Иванович', 'Бендор', 'Береговой, Георгий Тимофеевич', 'Березовой, Анатолий Николаевич', 'Би-би-си', 'Битва за космос', 'Болгария', 'Боливия', 'Большая российская энциклопедия', 'Большая российская энциклопедия (издательство)', 'Большая советская энциклопедия (третье издание)', 'Большой театр', 'Бор (Нижегородская область)', 'Борис Алексеевич Гагарин', 'Бразилия', 'Брежнев, Леонид Ильич', 'Бровко, Иван Карпович', 'Брянск', 'Бульвар Гагарина', 'Бульвар Гагарина (Брянск)', 'Бумажный солдат', 'Быковский, Валерий Фёдорович', 'Валентин Алексеевич Гагарин', 'Васютин, Владимир Владимирович', 'Венгрия', 'Верещетин, Владлен Степанович', 'Верховный Совет СССР', 'Верховье (Орловская область)', 'Вершинин, Константин Андреевич', 'Вечерняя Москва', 'Викитека', 'Викицитатник', 'Викторенко, Александр Степанович', 'Винница', 'Владимирская область', 'Внуково (аэропорт)', 'Воениздат', 'Военная служба', 'Военно-воздушная академия имени Ю. А. Гагарина', 'Военно-воздушная академия имени профессора Н. Е. Жуковского и Ю. А. Гагарина (Воронеж)', 'Военно-воздушная инженерная академия имени Н. Е. Жуковского', 'Военно-воздушные силы', 'Военно-воздушные силы СССР', 'Военный лётчик', 'Военный лётчик 1-го класса', 'Воздушная трасса', 'Воинское звание', 'Волга', 'Волгоград', 'Волк, Игорь Петрович', 'Волков, Александр Александрович (космонавт)', 'Волков, Владислав Николаевич', 'Волынов, Борис Валентинович', 'Ворошилов, Климент Ефремович', 'Воскресенский, Леонид Александрович', 'Восток-1', 'Восток (космический корабль)', 'Восток (ракета-носитель)', 'Восточно-Казахстанская область', 'Восточный (космодром)', 'Вострышев, Михаил Иванович', 'Восход (космический корабль)', 'Всемирное координированное время', 'Всенаправленный дальномерный радиомаяк', 'Всероссийский выставочный центр', 'ГАЗ-21', 'ГАЗ-М-20 «Победа»', 'Гагарин. Первый в космосе', 'Гагарин (Вологодская область)', 'Гагарин (Гегаркуникская область)', 'Гагарин (Джизакская область)', 'Гагарин (Смоленская область)', 'Гагарин (аэропорт)', 'Гагарин (значения)', 'Гагарин (лунный кратер)', 'Гагарин (мультфильм)', 'Гагарин (село)', 'Гагарин (станция)', 'Гагарина, Анна Тимофеевна', 'Гагарина, Валентина Ивановна', 'Гагарина, Галина Юрьевна', 'Гагарина, Елена Юрьевна', 'Гагаринит', 'Гагаринленд', 'Гагаринская (станция метро, Самара)', 'Гагаринская беседка', 'Гагаринский район', 'Гагаринский район (Смоленская область)', 'Гагаринский старт', 'Гагаринский тоннель', 'Гагарины', 'Галлай, Марк Лазаревич', 'Гамаль Абдель Насер', 'Гарольд Макмиллан', 'Гарышкер', 'Генерал-майор', 'Генеральный директор', 'Генеральный секретарь ЦК КПСС', 'Географические координаты', 'Герман, Алексей Алексеевич', 'Германская Демократическая Республика', 'Герой Советского Союза', 'Герой Социалистического Труда (НРБ)', 'Герой Социалистического Труда ЧССР', 'Герой Труда (Вьетнам)', 'Герой Труда Вьетнама', 'Герой Труда ЧССР', 'Гжатский радиоламповый завод', 'Гибель Юрия Гагарина', 'Главнокомандующий', 'Гладиолус', 'Глазков, Юрий Николаевич', 'Горбатко, Виктор Васильевич', 'Государственный архив Российской Федерации', 'Греция', 'Гречко, Георгий Михайлович', 'Гринвич', 'Гриссом, Вирджил Айвэн', 'Гриф секретности', 'Губарев, Алексей Александрович', 'Гуляев, Юрий Александрович', 'ДОСААФ', 'Деннис Тито', 'День космонавтики', 'Джанибеков, Владимир Александрович', 'Джунгарский Алатау', 'Дивногорск', 'Дипломный проект', 'Добровольский, Георгий Тимофеевич', 'Добронравов, Николай Николаевич', 'Добрый день, майор Гагарин', 'Доение', 'Доктор экономических наук', 'Документальное кино', 'Дом-музей Юрия Гагарина в Корзунове', 'Дорога в космос', 'Дружба народов (журнал)', 'Дубки (аэродром)', 'Дёмин, Лев Степанович', 'ЕКА', 'Евпатория', 'Европейское космическое агентство', 'Египет', 'Егоров, Борис Борисович', 'Елизавета II', 'Елисеев, Алексей Станиславович', 'Жалнин, Ярослав Владимирович', 'Жолобов, Виталий Михайлович', 'Жуковский (Московская область)', 'ЗИЛ-111', 'Западная область (1929—1937)', 'Заслуженный мастер спорта СССР', 'Звезда', 'Звёздные люди Земли', 'Звёздный (кинотеатр, Москва)', 'Звёздный городок', 'Здание аэроклуба (Саратов)', 'Земля', 'Зеркало недели', 'Златоуст', 'Знаете, каким он парнем был', 'Знак Гагарина', 'Золотая авиационная медаль ФАИ', 'Золотая медаль имени Ю. А. Гагарина', 'Зоя Алексеевна Гагарина', 'Зудов, Вячеслав Дмитриевич', 'Иван Фёдорович Гагарин', 'Иванченков, Александр Сергеевич', 'Ил-14', 'Ил-18', 'Импи, Крис', 'Индонезия', 'Интерфакс', 'Исаев, Алексей Михайлович', 'Исакович, Гарольд Григорьевич', 'Италия', 'Ишимбай', 'Йошкар-Ола', 'Казахстан', 'Каир', 'Калининград', 'Калуга', 'Каманин, Николай Петрович', 'Каменск-Шахтинский', 'Кандидат искусствоведения', 'Капитан (воинское звание)', 'Каталог почтовых марок СССР', 'Кизим, Леонид Денисович', 'Киргизия', 'Киржачский район', 'Кирилл Семёнович Москаленко', 'Кириллов, Анатолий Семёнович', 'Кировский завод', 'Классная квалификация военного лётчика', 'Кливленд', 'Климук, Пётр Ильич', 'Клинцы', 'Клушино (Смоленская область)', 'Ковалёнок, Владимир Васильевич', 'Код', 'Коломна', 'Командно-диспетчерский пункт', 'Комаров, Владимир Михайлович', 'Комикс', 'Коммерсантъ-Власть', 'Коммунистическая партия Советского Союза', 'Комсомол', 'Комсомольск-на-Амуре', 'Комсомольская правда', 'Комсомольская правда в Украине', 'Комсомольский-на-Амуре авиационный завод имени Ю. А. Гагарина', 'Континентальная хоккейная лига', 'Контрольно-пропускной пункт', 'Контрольный номер Библиотеки Конгресса', 'Королевская национальная библиотека Нидерландов', 'Королёв, Сергей Павлович', 'Королёв (город)', 'Косберг, Семён Ариевич', 'Космическая гонка', 'Космический полёт', 'Космическое пространство', 'Космонавт', 'Космонавт (фильм)', 'Космонавт Юрий Гагарин (судно)', 'Космонавтика', 'Космос как предчувствие', 'Красная звезда (газета)', 'Красная площадь', 'Кремация', 'Кремль', 'Крикалёв, Сергей Константинович', 'Кряж (аэродром)', 'Куадруш, Жаниу', 'Куба', 'Кубасов, Валерий Николаевич', 'Кубок Гагарина', 'Кумертау', 'Курск', 'Курская область', 'Курумоч (аэропорт)', 'Кызылординская область', 'Кыштым', 'Ла Скала', 'Лавейкин, Александр Иванович', 'Лавис, Крис', 'Лазарев, Василий Григорьевич', 'Латвийская национальная библиотека', 'Лебедев, Валентин Витальевич', 'Лебедев, Владимир Иванович (психолог)', 'Левитан, Юрий Борисович', 'Левченко, Анатолий Семёнович', 'Ледник', 'Ледник Гагарина', 'Лейбл звукозаписи', 'Лейтенант', 'Лениздат', 'Леонов, Алексей Архипович', 'Либерия', 'Лимасол', 'Лиственница курильская', 'Литейное производство', 'Лопота, Виталий Александрович', 'Луна', 'Луостари', 'Люберецкий техникум', 'Люберцы', 'Ляхов, Владимир Афанасьевич', 'Лётно-исследовательский институт имени М. М. Громова', 'Лётчик-космонавт', 'Лётчик-космонавт СССР', 'Мавзолей Ленина', 'Майор', 'Макаров, Олег Григорьевич', 'Малиновский, Родион Яковлевич', 'Малышев, Юрий Васильевич', 'Манаков, Геннадий Михайлович', 'Манаров, Муса Хираманович', 'Манчестер', 'Марка (акционерное общество)', 'Маршал', 'Машгиз (издательство)', 'Медаль «За безупречную службу»', 'Медаль «За безупречную службу» III степени', 'Медаль «За освоение целинных земель»', 'Медаль «Золотая Звезда» (СССР)', 'Медаль Ю. А. Гагарина (Роскосмос)', 'Медаль де Лаво', 'Международная авиационная федерация', 'Международная академия астронавтики', 'Международная федерация аэронавтики', 'Международный астрономический союз', 'Международный день полёта человека в космос', 'Международный идентификатор стандартных наименований', 'Международный конгресс астронавтики', 'Международный стандартный сериальный номер', 'Мелеуз', 'Мемориальная доска', 'Ми-4', 'МиГ-15', 'МиГ-15УТИ', 'МиГ-17', 'Микрорайон Гагарина (Сочи)', 'Минерал', 'Министерство обороны Российской Федерации', 'Мирзачульский район', 'Миронов, Арсений Дмитриевич', 'Михайлов, Павел Михайлович', 'Молодая гвардия (издательство)', 'Молочное хозяйство', 'Монпелье', 'Москва', 'Московский Кремль', 'Московский Кремль (музей-заповедник)', 'Московский комсомолец', 'Московское время', 'Мотокросс', 'Музей-квартира Юрия и Валентины Гагариных', 'Музей авиации и космонавтики (Париж)', 'Музрабадский район', 'Муляр, Дмитрий Сергеевич', 'Мурманская область', 'Мытищи', 'НАСА', 'НТВ', 'Набережная Космонавтов (Саратов)', 'Намибе (город)', 'Народная Республика Болгария', 'Наука и жизнь', 'Наука и религия', 'Национальная библиотека Австралии', 'Национальная библиотека Греции', 'Национальная библиотека Израиля', 'Национальная библиотека Испании', 'Национальная библиотека Польши', 'Национальная библиотека Португалии', 'Национальная библиотека Франции', 'Национальная библиотека Чешской Республики', 'Национальная библиотека Швеции', 'Национальная парламентская библиотека (Япония)', 'Национальный аэрокосмический университет имени Н. Е. Жуковского', 'Национальный орден Плайя-Хирон', 'Национальный орден Плайя Хирон', 'Национальный траур', 'Неаполь', 'Некрополь у Кремлёвской стены', 'Нелюбов, Григорий Григорьевич', 'Николаев, Андриян Григорьевич', 'Никосия', 'Новозыбков', 'Новокузнецк', 'Новороссийск', 'Новосибирск', 'Новосибирский метрополитен', 'Новости космонавтики', 'Новосёлово (Киржачский район)', 'ОКБ-23', 'Обсерватория Каподимонте', 'Объединённая Арабская Республика', 'Объединённый мемориальный музей-заповедник Ю. А. Гагарина', 'Объединённый мемориальный музей Ю. А. Гагарина', 'Огонёк (журнал)', 'Орбитальный самолёт', 'Орден «Георгий Димитров»', 'Орден «За заслуги в воздухоплавании» (Бразилия)', 'Орден «Звезда Республики Индонезии»', 'Орден «Крест Грюнвальда»', 'Орден Гагарина', 'Орден Дружбы народов', 'Орден Звезды Африки', 'Орден Звезды Индонезии', 'Орден Знамени (ВНР)', 'Орден Знамени ВНР', 'Орден Карла Маркса', 'Орден Клемента Готвальда', 'Орден Ленина', 'Орден Нила', 'Орден Трудового Красного Знамени', 'Оренбург', 'Оренбург-Центральный (аэропорт)', 'Оренбургское высшее военное авиационное Краснознамённое училище лётчиков', 'Осипов, Юрий Сергеевич (математик)', 'Осташев, Аркадий Ильич', 'Ош (город, Киргизия)', 'Оэйраш (город)', 'Павший астронавт', 'Памятник Гагарину (Москва)', 'Памятник Гагарину на Ленинском проспекте', 'Памятник Королёву и Гагарину', 'Памятник Юрию Гагарину (Ашхабад)', 'Памятник Юрию Гагарину (Байконур)', 'Памятник Юрию Гагарину (Брянск)', 'Памятник Юрию Гагарину (Калуга)', 'Памятник Юрию Гагарину (Нетания)', 'Памятник Юрию Гагарину (Саратов)', 'Памятник Юрию Гагарину (Сочи)', 'Памятник Юрию Гагарину (Ташкент)', 'Памятник Юрию Гагарину (Чебоксары)', 'Памятник Юрию Гагарину и Сергею Королёву (Энгельс)', 'Памятники Юрию Гагарину', 'Париж', 'Парк имени Юрия Гагарина', 'Парк имени Юрия Гагарина (Самара)', 'Парк покорителей космоса им. Юрия Гагарина', 'Парк покорителей космоса имени Ю. Гагарина', 'Пахмутова, Александра Николаевна', 'Пацаев, Виктор Иванович', 'Первая мировая война', 'Первушин, Антон Иванович', 'Первые полёты космонавтов различных стран мира', 'Первый отряд космонавтов СССР', 'Первый полёт человека в космос (омнибусная серия марок)', 'Первый полёт человека в космос (серия марок СССР)', 'Перегрузка (техника)', 'Перед полётом (памятник)', 'Пермь', 'Перник', 'Планетарий', 'Пловдив', 'Плоский штопор', 'Плотник', 'Площадь Гагарина', 'Площадь Гагарина (Москва)', 'Площадь Гагарина (станция МЦК)', 'Подгорное (Энгельсский район)', 'Подметки+', 'Подполковник', 'Поехали!', 'Позамантир, Раиса Дмитриевна', 'Познань', 'Покорителям космоса (Караганда)', 'Полковник', 'Польша', 'Поляков, Валерий Владимирович', 'Пономарёва, Валентина Леонидовна', 'Попов, Леонид Иванович', 'Попович, Павел Романович', 'Постановление ЦК КПСС и Совета Министров СССР', 'Похороны Юрия Гагарина и Владимира Серёгина', 'Почтовый блок', 'Почётное гражданство', 'Почётные граждане Новочеркасска', 'Почётный гражданин Севастополя', 'Почётный гражданин Смоленска', 'Почётный знак ВЛКСМ', 'Правительство Российской Федерации', 'Прага', 'Прачка', 'Председатель Президиума Верховного Совета СССР', 'Президент Российской Федерации', 'Приводная радиостанция', 'Приднестровская Молдавская Республика', 'Приднестровский государственный университет имени Тараса Шевченко', 'Приказ (акт управления)', 'Программа подготовки космонавтов к первому полёту', 'Прописка', 'Проспект Вернадского (Москва)', 'Проспект Гагарина', 'Противовоздушная оборона', 'Профессионально-педагогический колледж СГТУ имени Ю. А. Гагарина', 'Профессор', 'Прохоров, Александр Михайлович', 'Р-7 (семейство ракет-носителей)', 'РИА Новости', 'РКК «Энергия»', 'Рабоче-крестьянская Красная армия', 'Рабочий путь', 'Радар', 'Ракета-носитель', 'Ребров, Михаил Фёдорович', 'Революционер', 'Ремесленное училище (СССР)', 'Республика Кипр', 'Риека', 'Родильный дом', 'Рождественский, Валерий Ильич', 'Романенко, Юрий Викторович', 'Роскосмос', 'Российская Советская Федеративная Социалистическая Республика', 'Российская газета', 'Российская государственная библиотека', 'Российская национальная библиотека', 'Российский экономический университет имени Г. В. Плеханова', 'Россия', 'Руднев, Константин Николаевич', 'Рукавишников, Николай Николаевич', 'Русская Германия', 'Рюмин, Валерий Викторович', 'Рязанский радиоламповый завод', 'САЭ', 'СССР', 'Савиных, Виктор Петрович', 'Савицкая, Светлана Евгеньевна', 'Салах Дессуки', 'Самара', 'Санкт-Петербург', 'Саратов', 'Саратовская область', 'Саратовский государственный технический университет', 'Сарафанов, Геннадий Васильевич', 'Саркофаг', 'Сваливание', 'Сверхзвуковая скорость', 'Свинокомплекс', 'Севастополь', 'Севастьянов, Виталий Иванович', 'Северный флот ВМФ России', 'Сен-Дени', 'Сергей Павлович Королёв', 'Сергиев Посад', 'Серебров, Александр Александрович', 'Сержант', 'Серёгин, Владимир Сергеевич', 'Симферополь', 'Система жизнеобеспечения', 'Скафандр', 'Смеловка (Саратовская область)', 'Смирнов, Николай Иванович (адмирал)', 'Смоленск', 'Смоленская область', 'Совет Национальностей Верховного Совета СССР', 'Совет Союза Верховного Совета СССР', 'Совет министров СССР', 'Советская Россия (газета)', 'Советская армия', 'Советский рубль', 'Совхоз-техникум имени Ю. А. Гагарина', 'Созвездие Гагарина', 'Солнце', 'Соловьёв, Анатолий Яковлевич', 'Соловьёв, Владимир Алексеевич (космонавт)', 'София', 'Союз (космический корабль)', 'Союз МС-18', 'Союз Советских Социалистических Республик', 'Союз ТМА-21', 'Список депутатов Верховного Совета СССР 7-го созыва', 'Список депутатов Верховного Совета СССР 8-го созыва', 'Список зарубежных визитов Юрия Гагарина', 'Список почтовых марок, имеющих отношение к визитам Юрия Гагарина', 'Сплав', 'Спускаемый аппарат', 'Спутная струя', 'Стадион имени Юрия Алексеевича Гагарина', 'Старший лейтенант', 'Стерлитамак', 'Стратосфера', 'Стрекалов, Геннадий Михайлович', 'Су-15', 'Сумгаит', 'Сыпной тиф', 'ТАСС', 'Тамбов', 'Телестудия Роскосмоса', 'Теории заговора о Юрии Гагарине', 'Терешкова, Валентина Владимировна', 'Тимофей Матвеевич Матвеев', 'Тирасполь', 'Титан (элемент)', 'Титов, Владимир Георгиевич (космонавт)', 'Титов, Герман Степанович', 'Толстиков, Евгений Иванович', 'Тормозная двигательная установка', 'Тренчьянске Теплице', 'Третий рейх', 'Триумфальные ворота (Москва)', 'Троице-Сергиева лавра', 'Труд (газета)', 'Трудовые резервы (спортивное общество)', 'Ту-104', 'Туктибай', 'Тунис (город)', 'Турандот (опера)', 'Туринск', 'Тюмень', 'Уайт, Эдвард Хиггинс', 'Угон граждан СССР на работу в Германию', 'Узбекистан', 'Укрощение огня', 'Улица Возрождения (Санкт-Петербург)', 'Улица Гагарина', 'Университетская система документации', 'Устинов, Дмитрий Фёдорович', 'ФРГ', 'Фамагуста', 'Федеральное космическое агентство', 'Феоктистов, Константин Петрович', 'Филателистическая гагариниана', 'Филипченко, Анатолий Васильевич', 'Финляндия', 'Форос', 'Франция', 'Хабаровск', 'Хемниц', 'Хоккей с шайбой', 'Храм Христа Спасителя', 'Хрунов, Евгений Васильевич', 'Хрущёв, Никита Сергеевич', 'Хрущёв Никита Сергеевич', 'Хрущёвская антирелигиозная кампания', 'Хьюстон', 'ЦСКА (хоккейный клуб, Москва)', 'ЦСКБ-Прогресс', 'Центр подготовки космонавтов', 'Центр подготовки космонавтов имени Ю. А. Гагарина', 'Центр управления полётами', 'Центральный Дом Советской Армии', 'Центральный дом авиации и космонавтики', 'Центральный комитет ВЛКСМ', 'Циклограмма пуска', 'Циолковский, Константин Эдуардович', 'Циолковский (город)', 'Частота', 'Чаффи, Роджер', 'Челомбитько, Анатолий Михайлович', 'Челябинск', 'Чернов, Юрий Львович', 'Черногория', 'Черток, Борис Евсеевич', 'Чехословакия', 'Шаталов, Владимир Александрович', 'Швеция', 'Школа рабочей молодёжи', 'Шонин, Георгий Степанович', 'Штаб-квартира ООН', 'Штопор (пилотаж)', 'Щербовский, Мацек', 'Щёлково', 'Щёлково-3', 'Энгельс (авиабаза)', 'Энгельс (город)', 'Эшелон (авиация)', 'Юбилейная медаль «40 лет Вооружённых Сил СССР»', 'Юбилейная медаль «50 лет Вооружённых Сил СССР»', 'Юбилейная медаль «Двадцать лет Победы в Великой Отечественной войне 1941—1945 гг.»', 'Южно-Сахалинск', 'Юрий Гагарин (фильм)', 'Юрий Гагарин в культуре и искусстве', 'Юрьева ночь (космонавтика)', 'Як-18', 'Ярославль']
718
179
['Большая российская энциклопедия', 'Контрольный номер Библиотеки Конгресса', 'Национальная библиотека Франции', 'VIAF', 'Gemeinsame Normdatei', 'Национальная библиотека Польши', 'Латвийская национальная библиотека', 'Национальная библиотека Чешской Республики', 'Университетская система документации', 'WorldCat', 'Российская государственная библиотека', 'Национальная библиотека Испании', 'Национальная парламентская библиотека (Япония)', 'Осипов, Юрий Сергеевич (математик)', 'Национальная библиотека Израиля', 'Национальная библиотека Португалии', 'Национальная библиотека Греции', 'Российская национальная библиотека', 'NUKAT', 'Международный идентификатор стандартных наименований', 'CiNii', 'Национальная библиотека Швеции', 'Королевская национальная библиотека Нидерландов', 'Национальная библиотека Австралии', 'Wayback Machine', 'Александрия']
27

In [ ]:
!kaggle datasets download -d r1chardson/the-world-university-rankings-2011-2023

Downloading the-world-university-rankings-2011-2023.zip to /content
  0% 0.00/1.27M [00:00<?, ?B/s]
100% 1.27M/1.27M [00:00<00:00, 157MB/s]

In [ ]:
import zipfile

with zipfile.ZipFile("the-world-university-rankings-2011-2023.zip","r") as zip_ref:

    # extracting content in the zipfile
    zip_ref.extractall()

In [ ]:
!ls

2011_rankings.csv  2020_rankings.csv
2012_rankings.csv  2021_rankings.csv
2013_rankings.csv  2022_rankings.csv
2014_rankings.csv  2023_rankings.csv
2015_rankings.csv  education.xlsx
2016_rankings.csv  kaggle.json
2017_rankings.csv  sample_data
2018_rankings.csv  the-world-university-rankings-2011-2023.zip
2019_rankings.csv

In [ ]:
df.info()

NameError: ignored

In [ ]:
# reading the contents of the "NetFlix.csv"
df = pd.read_csv("2023_rankings.csv")

# printing first 6 raws of the dataframe
df.head(100)

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,96.4,10,92.3,5,99.7,1,99.0,...,28,United Kingdom,"20,965",10.6,42%,48 : 52,University of Oxford,"Accounting & Finance,General Engineering,Commu...",False,False
1,20,2,Harvard University,95.2,20,94.8,1,99.0,3,99.3,...,214,United States,"21,887",9.6,25%,50 : 50,Harvard University,"Mathematics & Statistics,Civil Engineering,Lan...",False,False
2,30,=3,University of Cambridge,94.8,30,90.9,7,99.5,2,97.0,...,34,United Kingdom,"20,185",11.3,39%,47 : 53,University of Cambridge,"Business & Management,General Engineering,Art,...",False,False
3,40,=3,Stanford University,94.8,40,94.2,2,96.7,7,99.8,...,223,United States,"16,164",7.1,24%,46 : 54,Stanford University,"Physics & Astronomy,Computer Science,Politics ...",False,False
4,50,5,Massachusetts Institute of Technology,94.2,50,90.7,8,93.6,11,99.8,...,119,United States,"11,415",8.2,33%,40 : 60,Massachusetts Institute of Technology,"Mathematics & Statistics,Languages, Literature...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,960,=95,Institut Polytechnique de Paris,63.6,960,58.5,68,58.8,85,64.8,...,38,France,"5,999",6.7,41%,24 : 76,Institut Polytechnique de Paris,"Other Health,Biological Sciences,Languages, Li...",False,False
96,970,=95,Nanjing University,63.6,970,58.4,69,58.2,91,74.3,...,568,China,"36,426",16.5,8%,54 : 46,Nanjing University,"Other Health,Sociology,Economics & Econometric...",False,False
97,980,98,Vanderbilt University,63.5,980,49.5,113,47.5,153,96.5,...,657,United States,"12,696",3.8,15%,55 : 45,Vanderbilt University,"Psychology,Politics & International Studies (i...",False,False
98,990,=99,City University of Hong Kong,63.4,990,47.2,130,53.0,120,79.9,...,2,Hong Kong,"9,099",12.1,62%,54 : 46,City University of Hong Kong CityU HK,"Civil Engineering,Chemistry,Architecture,Psych...",False,False
99,1000,=99,RWTH Aachen University,63.4,1000,56.8,73,64.5,64,66.1,...,404,Germany,"39,738",50.0,28%,33 : 67,RWTH Aachen University,"Civil Engineering,Economics & Econometrics,Lan...",False,False

In [ ]:
my_df =df[['rank','name','scores_overall','scores_teaching','scores_research','location','stats_number_students']].copy()

In [ ]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2345 entries, 0 to 2344
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   2345 non-null   object
 1   name                   2345 non-null   object
 2   scores_overall         1799 non-null   object
 3   scores_teaching        1799 non-null   float64
 4   scores_research        1799 non-null   float64
 5   location               2345 non-null   object
 6   stats_number_students  2345 non-null   object
dtypes: float64(2), object(5)
memory usage: 128.4+ KB

In [ ]:
my_df

,rank,name,scores_overall,scores_teaching,scores_research,location,stats_number_students
0,1,University of Oxford,96.4,92.3,99.7,United Kingdom,"20,965"
1,2,Harvard University,95.2,94.8,99.0,United States,"21,887"
2,=3,University of Cambridge,94.8,90.9,99.5,United Kingdom,"20,185"
3,=3,Stanford University,94.8,94.2,96.7,United States,"16,164"
4,5,Massachusetts Institute of Technology,94.2,90.7,93.6,United States,"11,415"
...,...,...,...,...,...,...,...
2340,Reporter,York St John University,NaN,NaN,NaN,United Kingdom,"6,315"
2341,Reporter,"Yusuf Maitama Sule University, Kano",NaN,NaN,NaN,Nigeria,"12,880"
2342,Reporter,Zhytomyr Polytechnic State University,NaN,NaN,NaN,Ukraine,"3,869"
2343,Reporter,Ziauddin University,NaN,NaN,NaN,Pakistan,"4,906"
2344,Reporter,Zarqa University,NaN,NaN,NaN,Jordan,"5,768"

In [ ]:
my_df.isnull().values.any()

True

In [ ]:
my_df.isnull().sum()

rank                       0
name                       0
scores_overall           546
scores_teaching          546
scores_research          546
location                   0
stats_number_students      0
dtype: int64

In [ ]:
df.isnull().sum().sum()

3373

In [ ]:
my_df.isna().sum()/(len(df))*100

rank                      0.000000
name                      0.000000
scores_overall           23.283582
scores_teaching          23.283582
scores_research          23.283582
location                  0.000000
stats_number_students     0.000000
dtype: float64

In [ ]:
my_df.isnull().sum()/(len(df))*100

rank                      0.000000
name                      0.000000
scores_overall           23.283582
scores_teaching          23.283582
scores_research          23.283582
location                  0.000000
stats_number_students     0.000000
dtype: float64

In [ ]:
df2 = my_df.dropna()

In [ ]:
df2

,rank,name,scores_overall,scores_teaching,scores_research,location,stats_number_students
0,1,University of Oxford,96.4,92.3,99.7,United Kingdom,"20,965"
1,2,Harvard University,95.2,94.8,99.0,United States,"21,887"
2,=3,University of Cambridge,94.8,90.9,99.5,United Kingdom,"20,185"
3,=3,Stanford University,94.8,94.2,96.7,United States,"16,164"
4,5,Massachusetts Institute of Technology,94.2,90.7,93.6,United States,"11,415"
...,...,...,...,...,...,...,...
1794,1501+,Yamaguchi University,10.4–18.3,21.3,12.3,Japan,"10,724"
1795,1501+,Yanshan University,10.4–18.3,17.2,10.9,China,"38,649"
1796,1501+,Yeditepe University,10.4–18.3,18.8,12.2,Turkey,"17,038"
1797,1501+,Yuri Gagarin State Technical University of Sar...,10.4–18.3,12.5,8.9,Russian Federation,"28,280"
1798,1501+,Zonguldak Bülent Ecevit University,10.4–18.3,13.2,8.2,Turkey,"28,319"

In [ ]:
rslt_df = df2[df2['location'] == 'Russian Federation']

In [ ]:
rslt_df

,rank,name,scores_overall,scores_teaching,scores_research,location,stats_number_students
163,=163,Lomonosov Moscow State University,56.9,81.0,72.9,Russian Federation,"32,625"
221,201–250,Moscow Institute of Physics and Technology (MIPT),51.2–54.3,55.7,46.8,Russian Federation,"6,083"
330,301–350,Peter the Great St Petersburg Polytechnic Univ...,47.0–48.7,31.1,23.7,Russian Federation,"16,375"
433,401–500,HSE University,42.1–44.9,32.5,45.3,Russian Federation,"32,102"
461,401–500,National Research Nuclear University MEPhI,42.1–44.9,45.3,41.7,Russian Federation,"5,016"
...,...,...,...,...,...,...,...
1773,1501+,Tomsk State University of Control Systems and ...,10.4–18.3,17.3,11.2,Russian Federation,"6,185"
1777,1501+,University of Tyumen,10.4–18.3,16.6,12.7,Russian Federation,"11,569"
1778,1501+,Ufa State Aviation Technical University,10.4–18.3,15.8,9.5,Russian Federation,"8,865"
1787,1501+,Voronezh State University,10.4–18.3,18.8,10.2,Russian Federation,"15,534"
1797,1501+,Yuri Gagarin State Technical University of Sar...,10.4–18.3,12.5,8.9,Russian Federation,"28,280"

In [ ]:
rslt_df.reset_index(drop=True, inplace=True)

In [ ]:
rslt_df

,rank,name,scores_overall,scores_teaching,scores_research,location,stats_number_students
0,=163,Lomonosov Moscow State University,56.9,81.0,72.9,Russian Federation,"32,625"
1,201–250,Moscow Institute of Physics and Technology (MIPT),51.2–54.3,55.7,46.8,Russian Federation,"6,083"
2,301–350,Peter the Great St Petersburg Polytechnic Univ...,47.0–48.7,31.1,23.7,Russian Federation,"16,375"
3,401–500,HSE University,42.1–44.9,32.5,45.3,Russian Federation,"32,102"
4,401–500,National Research Nuclear University MEPhI,42.1–44.9,45.3,41.7,Russian Federation,"5,016"
...,...,...,...,...,...,...,...
71,1501+,Tomsk State University of Control Systems and ...,10.4–18.3,17.3,11.2,Russian Federation,"6,185"
72,1501+,University of Tyumen,10.4–18.3,16.6,12.7,Russian Federation,"11,569"
73,1501+,Ufa State Aviation Technical University,10.4–18.3,15.8,9.5,Russian Federation,"8,865"
74,1501+,Voronezh State University,10.4–18.3,18.8,10.2,Russian Federation,"15,534"
75,1501+,Yuri Gagarin State Technical University of Sar...,10.4–18.3,12.5,8.9,Russian Federation,"28,280"

In [ ]:
rslt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   76 non-null     object
 1   name                   76 non-null     object
 2   scores_overall         76 non-null     object
 3   scores_teaching        76 non-null     float64
 4   scores_research        76 non-null     float64
 5   location               76 non-null     object
 6   stats_number_students  76 non-null     object
dtypes: float64(2), object(5)
memory usage: 4.3+ KB

In [ ]:
rslt_df['scores_overall']=rslt_df['scores_overall'].str[-4:]

<ipython-input-46-08424674b615>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rslt_df['scores_overall']=rslt_df['scores_overall'].str[-4:]

In [ ]:
rslt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   76 non-null     object
 1   name                   76 non-null     object
 2   scores_overall         76 non-null     object
 3   scores_teaching        76 non-null     float64
 4   scores_research        76 non-null     float64
 5   location               76 non-null     object
 6   stats_number_students  76 non-null     object
dtypes: float64(2), object(5)
memory usage: 4.3+ KB

In [ ]:
rslt_df

,rank,name,scores_overall,scores_teaching,scores_research,location,stats_number_students
0,=163,Lomonosov Moscow State University,56.9,81.0,72.9,Russian Federation,"32,625"
1,201–250,Moscow Institute of Physics and Technology (MIPT),54.3,55.7,46.8,Russian Federation,"6,083"
2,301–350,Peter the Great St Petersburg Polytechnic Univ...,48.7,31.1,23.7,Russian Federation,"16,375"
3,401–500,HSE University,44.9,32.5,45.3,Russian Federation,"32,102"
4,401–500,National Research Nuclear University MEPhI,44.9,45.3,41.7,Russian Federation,"5,016"
...,...,...,...,...,...,...,...
71,1501+,Tomsk State University of Control Systems and ...,18.3,17.3,11.2,Russian Federation,"6,185"
72,1501+,University of Tyumen,18.3,16.6,12.7,Russian Federation,"11,569"
73,1501+,Ufa State Aviation Technical University,18.3,15.8,9.5,Russian Federation,"8,865"
74,1501+,Voronezh State University,18.3,18.8,10.2,Russian Federation,"15,534"
75,1501+,Yuri Gagarin State Technical University of Sar...,18.3,12.5,8.9,Russian Federation,"28,280"

In [ ]:
rslt_df['scores_overall'] = rslt_df['scores_overall'].astype('float64')

<ipython-input-49-b4e0b3627173>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rslt_df['scores_overall'] = rslt_df['scores_overall'].astype('float64')

In [ ]:
rslt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   76 non-null     object
 1   name                   76 non-null     object
 2   scores_overall         76 non-null     float64
 3   scores_teaching        76 non-null     float64
 4   scores_research        76 non-null     float64
 5   location               76 non-null     object
 6   stats_number_students  76 non-null     object
dtypes: float64(3), object(4)
memory usage: 4.3+ KB

In [ ]:
dd=rslt_df

In [ ]:
dd['stats_number_students'] = [x.replace(',', '.') for x in dd['stats_number_students']]

<ipython-input-52-513b05614dc4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['stats_number_students'] = [x.replace(',', '.') for x in dd['stats_number_students']]

In [ ]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   76 non-null     object
 1   name                   76 non-null     object
 2   scores_overall         76 non-null     float64
 3   scores_teaching        76 non-null     float64
 4   scores_research        76 non-null     float64
 5   location               76 non-null     object
 6   stats_number_students  76 non-null     object
dtypes: float64(3), object(4)
memory usage: 4.3+ KB

In [ ]:
dd['scores_overall'] = dd['scores_overall'].astype('float64')

<ipython-input-54-a58060986030>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dd['scores_overall'] = dd['scores_overall'].astype('float64')

In [ ]:
dd.to_excel("education_ru.xlsx", sheet_name='education_ru')
from google.colab import files
files.download('education_ru.xlsx')