In [1]:
pip install pycaret

Collecting pycaret
  Obtaining dependency information for pycaret from https://files.pythonhosted.org/packages/eb/43/ec8d59a663e0a1a67196b404ec38ccb0051708bad74a48c80d96c61dd0e5/pycaret-3.2.0-py3-none-any.whl.metadata
  Downloading pycaret-3.2.0-py3-none-any.whl.metadata (17 kB)
Collecting category-encoders>=2.4.0 (from pycaret)
  Obtaining dependency information for category-encoders>=2.4.0 from https://files.pythonhosted.org/packages/7f/e5/79a62e5c9c9ddbfa9ff5222240d408c1eeea4e38741a0dc8343edc7ef1ec/category_encoders-2.6.3-py2.py3-none-any.whl.metadata
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: cloudpickle in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (2.2.1)
Collecting deprecation>=2.1.0 (from pycaret)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting imbalanced-learn>=0.8.1 (from pycaret)
  Obtaining dependency information for imbalanced-learn>=0.8.1 from https://files.pythonhosted.org/packages/a3/9e/fbe60a768502af54563dcb59ca7856f5a8833b3ad5ada658922e1ab09b7f/imbalanced_learn-0.11.0-py3-none-any.whl.metadata
  Downloading imbalanced_learn-0.11.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: importlib-metadata>=4.12.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (6.8.0)
Requirement already satisfied: ipython>=5.5.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (8.14.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (7.7.0)
Requirement already satisfied: jinja2>=1.2 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (3.1.2)
Requirement already satisfied: joblib>=1.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (1.3.0)
Collecting kaleido>=0.2.1 (from pycaret)
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 26.5 MB/s eta 0:00:0000:0100:01
Collecting lightgbm>=3.0.0 (from pycaret)
  Obtaining dependency information for lightgbm>=3.0.0 from https://files.pythonhosted.org/packages/b8/9d/1ce80cee7c5ef60f2fcc7e9fa97f29f7a8de3dc5a08922b3b2f1e9106481/lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata
  Downloading lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: markupsafe>=2.0.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (2.1.3)
Requirement already satisfied: matplotlib<=3.6,>=3.3.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (3.5.2)
Requirement already satisfied: nbformat>=4.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (5.9.1)
Requirement already satisfied: numba>=0.55.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (0.57.1)
Requirement already satisfied: numpy<1.27,>=1.21 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (1.21.6)
Requirement already satisfied: pandas<2.0.0,>=1.3.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (1.4.2)
Collecting plotly-resampler>=0.8.3.1 (from pycaret)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/08/1d/87d4ed45c26226630bcb0a205ff006c00645cc68977e22c0f6f16a7f5d2b/plotly_resampler-0.9.1-py3-none-any.whl.metadata
  Downloading plotly_resampler-0.9.1-py3-none-any.whl.metadata (12 kB)
Collecting plotly>=5.0.0 (from pycaret)
  Obtaining dependency information for plotly>=5.0.0 from https://files.pythonhosted.org/packages/a8/07/72953cf70e3bd3a24cbc3e743e6f8539abe6e3e6d83c3c0c83426eaffd39/plotly-5.18.0-py3-none-any.whl.metadata
  Downloading plotly-5.18.0-py3-none-any.whl.metadata (7.0 kB)
Collecting pmdarima!=1.8.1,<3.0.0,>=1.8.0 (from pycaret)
  Obtaining dependency information for pmdarima!=1.8.1,<3.0.0,>=1.8.0 from https://files.pythonhosted.org/packages/a2/14/cd7417d90312ad6de4e5bb48d98f0b89e77bb427f5b80495074ab25cd13b/pmdarima-2.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata
  Downloading pmdarima-2.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: psutil>=5.9.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (5.9.5)
Collecting pyod>=1.0.8 (from pycaret)
  Downloading pyod-1.1.2.tar.gz (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.5/160.5 kB 34.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests>=2.27.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (2.31.0)
Collecting schemdraw==0.15 (from pycaret)
  Downloading schemdraw-0.15-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 20.3 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn<1.3.0,>=1.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pycaret) (1.0.2)
Collecting scikit-plot>=0.3.7 (from pycaret)
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting scipy~=1.10.1 (from pycaret)
  Downloading scipy-1.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 52.1 MB/s eta 0:00:0000:0100:01
Collecting sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 (from pycaret)
  Obtaining dependency information for sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 from https://files.pythonhosted.org/packages/0f/70/a791db68c6f6922eb9e79baf1466263147a487c5b7ba7813f5868901e032/sktime-0.21.1-py3-none-any.whl.metadata
  Downloading sktime-0.21.1-py3-none-any.whl.metadata (25 kB)
Collecting statsmodels>=0.12.1 (from pycaret)
  Downloading statsmodels-0.14.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 99.7 MB/s eta 0:00:0000:0100:01
Collecting tbats>=1.1.3 (from pycaret)
  Downloading tbats-1.1.3-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 9.9 MB/s eta 0:00:00
Collecting tqdm>=4.62.0 (from pycaret)
  Obtaining dependency information for tqdm>=4.62.0 from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 15.6 MB/s eta 0:00:00
Collecting xxhash (from pycaret)
  Obtaining dependency information for xxhash from https://files.pythonhosted.org/packages/63/93/812d78f70145c68c4e64533f4d625bea01236f27698febe15f0ceebc1566/xxhash-3.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading xxhash-3.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting yellowbrick>=1.4 (from pycaret)
  Downloading yellowbrick-1.5-py3-none-any.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.6/282.6 kB 51.4 MB/s eta 0:00:00
Collecting wurlitzer (from pycaret)
  Downloading wurlitzer-3.0.3-py3-none-any.whl (7.3 kB)
Collecting patsy>=0.5.1 (from category-encoders>=2.4.0->pycaret)
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 49.7 MB/s eta 0:00:00
Requirement already satisfied: packaging in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from deprecation>=2.1.0->pycaret) (23.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from imbalanced-learn>=0.8.1->pycaret) (3.2.0)
Requirement already satisfied: zipp>=0.5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.16.2)
Requirement already satisfied: backcall in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.18.2)
Requirement already satisfied: matplotlib-inline in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.6.2)
Requirement already satisfied: traitlets>=5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.9.0)
Requirement already satisfied: typing-extensions in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (4.7.1)
Requirement already satisfied: pexpect>4.3 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (6.13.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (3.6.4)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (1.1.4)
Requirement already satisfied: cycler>=0.10 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (9.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: fastjsonschema in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from nbformat>=4.2.0->pycaret) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from nbformat>=4.2.0->pycaret) (4.18.4)
Requirement already satisfied: jupyter-core in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from nbformat>=4.2.0->pycaret) (5.3.1)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from numba>=0.55.0->pycaret) (0.40.1)
Requirement already satisfied: pytz>=2020.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pandas<2.0.0,>=1.3.0->pycaret) (2023.3)
Collecting tenacity>=6.2.0 (from plotly>=5.0.0->pycaret)
  Obtaining dependency information for tenacity>=6.2.0 from https://files.pythonhosted.org/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.3-py3-none-any.whl.metadata
  Downloading tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting dash<3.0.0,>=2.11.0 (from plotly-resampler>=0.8.3.1->pycaret)
  Obtaining dependency information for dash<3.0.0,>=2.11.0 from https://files.pythonhosted.org/packages/00/69/d0ee9c6524678e98d336464d5c898182794c6b2ba1e5507bc7010a126ce2/dash-2.14.1-py3-none-any.whl.metadata
  Downloading dash-2.14.1-py3-none-any.whl.metadata (11 kB)
Collecting orjson<4.0.0,>=3.8.0 (from plotly-resampler>=0.8.3.1->pycaret)
  Obtaining dependency information for orjson<4.0.0,>=3.8.0 from https://files.pythonhosted.org/packages/34/c0/faa1eb343588cad0afa7a2d36ec4a873e65b99c291342fe375d4da1b3a26/orjson-3.9.10-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading orjson-3.9.10-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 11.3 MB/s eta 0:00:00
Collecting trace-updater>=0.0.8 (from plotly-resampler>=0.8.3.1->pycaret)
  Downloading trace_updater-0.0.9.1-py3-none-any.whl (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 36.4 MB/s eta 0:00:00
Collecting tsdownsample==0.1.2 (from plotly-resampler>=0.8.3.1->pycaret)
  Downloading tsdownsample-0.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 110.7 MB/s eta 0:00:00
Collecting Cython!=0.29.18,!=0.29.31,>=0.29 (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret)
  Obtaining dependency information for Cython!=0.29.18,!=0.29.31,>=0.29 from https://files.pythonhosted.org/packages/40/19/46acdb9d0cad7cc2a80f721d6132dc50f7864d1598d9298e83b78c7d6bf9/Cython-3.0.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading Cython-3.0.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: urllib3 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (1.26.15)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (59.8.0)
Requirement already satisfied: six in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pyod>=1.0.8->pycaret) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2023.7.22)
Collecting deprecated>=1.2.13 (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret)
  Obtaining dependency information for deprecated>=1.2.13 from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd59ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl.metadata
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-base<0.6.0 (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret)
  Obtaining dependency information for scikit-base<0.6.0 from https://files.pythonhosted.org/packages/e1/05/c42d5834896d0c112e76bb5b1ff0532e06cda405ae3154be5593a4aa8f37/scikit_base-0.5.2-py3-none-any.whl.metadata
  Downloading scikit_base-0.5.2-py3-none-any.whl.metadata (8.6 kB)
Collecting Flask<3.1,>=1.0.4 (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Obtaining dependency information for Flask<3.1,>=1.0.4 from https://files.pythonhosted.org/packages/36/42/015c23096649b908c809c69388a805a571a3bea44362fe87e33fc3afa01f/flask-3.0.0-py3-none-any.whl.metadata
  Downloading flask-3.0.0-py3-none-any.whl.metadata (3.6 kB)
Collecting Werkzeug<3.1 (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Obtaining dependency information for Werkzeug<3.1 from https://files.pythonhosted.org/packages/c3/fc/254c3e9b5feb89ff5b9076a23218dafbc99c96ac5941e900b71206e6313b/werkzeug-3.0.1-py3-none-any.whl.metadata
  Downloading werkzeug-3.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting dash-html-components==2.0.0 (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0 (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-table==5.0.0 (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting retrying (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting ansi2html (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret)
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: nest-asyncio in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from deprecated>=1.2.13->sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (1.15.0)
Requirement already satisfied: debugpy>=1.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (7.3.4)
Requirement already satisfied: tornado>=6.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.9.2)
Requirement already satisfied: ptyprocess>=0.5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: wcwidth in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: notebook>=4.4.1 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.5.4)
Requirement already satisfied: platformdirs>=2.5 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.9.1)
Requirement already satisfied: executing>=1.2.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from stack-data->ipython>=5.5.0->pycaret) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: pure-eval in /opt/saturncloud/envs/saturn/lib/python3.9/site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)

In [2]:
import pycaret

In [7]:
from pycaret.datasets import get_data
nba = get_data('nba')

,Name,GP,MIN,PTS,FGM,FGA,FG%,3P Made,3PA,3P%,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,TARGET_5Yrs
0,Brandon Ingram,36,27.4,7.4,2.6,7.6,34.7,0.5,2.1,25.0,...,2.3,69.9,0.7,3.4,4.1,1.9,0.4,0.4,1.3,0
1,Andrew Harrison,35,26.9,7.2,2.0,6.7,29.6,0.7,2.8,23.5,...,3.4,76.5,0.5,2.0,2.4,3.7,1.1,0.5,1.6,0
2,JaKarr Sampson,74,15.3,5.2,2.0,4.7,42.2,0.4,1.7,24.4,...,1.3,67.0,0.5,1.7,2.2,1.0,0.5,0.3,1.0,0
3,Malik Sealy,58,11.6,5.7,2.3,5.5,42.6,0.1,0.5,22.6,...,1.3,68.9,1.0,0.9,1.9,0.8,0.6,0.1,1.0,1
4,Matt Geiger,48,11.5,4.5,1.6,3.0,52.4,0.0,0.1,0.0,...,1.9,67.4,1.0,1.5,2.5,0.3,0.3,0.4,0.8,1

In [8]:
# check version
from pycaret.utils import version
version()

'3.2.0'

In [30]:
from pycaret.classification import *
pycar = setup(nba, target = 'TARGET_5Yrs')

In [32]:
from pycaret.classification import *
reg1 = setup(data = nba, target = 'TARGET_5Yrs', train_size = 0.6)

In [33]:
from pycaret.datasets import get_data
income = get_data('income')
from pycaret.classification import *
model = setup(data = income, target = 'income >50K')

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income >50K
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [34]:
#import the hepatitis dataset from PyCaret repository
from pycaret.datasets import get_data
nba = get_data('hepatitis')

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,0,30,2,1.0,2,2,2,2,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.0,18.0,4.0,NaN,1
1,0,50,1,1.0,2,1,2,2,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.0,42.0,3.5,NaN,1
2,0,78,1,2.0,2,1,2,2,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.0,32.0,4.0,NaN,1
3,0,31,1,NaN,1,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.0,52.0,4.0,80.0,1
4,0,34,1,2.0,2,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,200.0,4.0,NaN,1

In [36]:
from pycaret.classification import*
clf1 = setup(nba, target = 'Class')
clf1

In [38]:
from pycaret.datasets import get_data
emp = get_data('employee')

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,department,salary,left
0,0.38,0.53,2,157,3,0,0,sales,low,1
1,0.80,0.86,5,262,6,0,0,sales,medium,1
2,0.11,0.88,7,272,4,0,0,sales,medium,1
3,0.72,0.87,5,223,5,0,0,sales,low,1
4,0.37,0.52,2,159,3,0,0,sales,low,1

In [39]:
from pycaret.classification import *
model = setup(data = emp, target = 'left', ordinal_features = {'salary' : ['low', 'medium', 'high']})

In [41]:
from pycaret.datasets import get_data
inc = get_data('income')

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income >50K
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [46]:
from pycaret.datasets import get_data
nba = get_data('blood')

   Recency  Frequency  Monetary  Time  Class
0        2         50     12500    98      1
1        0         13      3250    28      1
2        1         16      4000    35      1
3        2         20      5000    45      1
4        1         24      6000    77      0